"""
services/pdf_generator.py
PDF report generator for interview sessions and resume analyses.
Uses ReportLab.
"""
import logging
from datetime import datetime
from config import REPORTS_DIR

log = logging.getLogger(__name__)


def _base_doc(filepath, title_text, subtitle_text):
    """Create a ReportLab SimpleDocTemplate with standard styling."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate

    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        topMargin=2*cm, bottomMargin=2*cm,
        leftMargin=2*cm, rightMargin=2*cm
    )
    styles = {
        "title": ParagraphStyle("title", fontSize=22, fontName="Helvetica-Bold",
                                 textColor=colors.HexColor("#00D4FF"),
                                 alignment=1, spaceAfter=4),
        "subtitle": ParagraphStyle("subtitle", fontSize=12,
                                    textColor=colors.HexColor("#8B5CF6"),
                                    alignment=1, spaceAfter=16),
        "h2":   ParagraphStyle("h2", fontSize=14, fontName="Helvetica-Bold",
                                textColor=colors.HexColor("#3B82F6"),
                                spaceBefore=12, spaceAfter=6),
        "body": ParagraphStyle("body", fontSize=10,
                                textColor=colors.HexColor("#1F2937"),
                                spaceAfter=4, leading=14),
        "footer": ParagraphStyle("footer", fontSize=8,
                                  textColor=colors.grey, alignment=1),
    }
    return doc, styles


def generate_interview_report(session_data: dict) -> str:
    """
    Generate a PDF report for a completed interview session.
    Returns the filepath on success, empty string on failure.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import (Paragraph, Spacer, Table, TableStyle,
                                         HRFlowable)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath  = str(REPORTS_DIR / f"interview_report_{timestamp}.pdf")
        doc, S    = _base_doc(filepath, "AI Interview Coach", "Interview Performance Report")

        story = [
            Paragraph("AI Interview Coach", S["title"]),
            Paragraph("Interview Performance Report", S["subtitle"]),
            HRFlowable(width="100%", thickness=1, color=colors.HexColor("#00D4FF")),
            Spacer(1, 0.4*cm),
        ]

        # Meta table
        meta = [
            ["Date",       session_data.get("created_at", "")[:19]],
            ["Domain",     session_data.get("domain", "N/A")],
            ["Mode",       session_data.get("mode", "N/A")],
            ["Difficulty", session_data.get("difficulty", "N/A")],
            ["Score",      f"{session_data.get('score', 0):.1f} / 10"],
            ["Duration",   f"{session_data.get('duration', 0)} min"],
        ]
        t = Table(meta, colWidths=[4*cm, 13*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",     (0,0), (0,-1), colors.HexColor("#EFF6FF")),
            ("TEXTCOLOR",      (0,0), (0,-1), colors.HexColor("#1E40AF")),
            ("FONTNAME",       (0,0), (0,-1), "Helvetica-Bold"),
            ("FONTSIZE",       (0,0), (-1,-1), 10),
            ("ROWBACKGROUNDS", (0,0), (-1,-1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("GRID",           (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ("TOPPADDING",     (0,0), (-1,-1), 6),
            ("BOTTOMPADDING",  (0,0), (-1,-1), 6),
        ]))
        story += [t, Spacer(1, 0.6*cm)]

        # Q&A review
        questions  = session_data.get("questions", [])
        answers    = session_data.get("answers", [])
        feedbacks  = session_data.get("feedback_list", [])

        if questions:
            story.append(Paragraph("Interview Q&A Review", S["h2"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1")))
            for i, q in enumerate(questions):
                story.append(Spacer(1, 0.2*cm))
                story.append(Paragraph(f"<b>Q{i+1}:</b> {q}", S["body"]))
                ans = answers[i] if i < len(answers) else "No answer provided"
                story.append(Paragraph(f"<b>Answer:</b> {ans}", S["body"]))
                if i < len(feedbacks) and feedbacks[i]:
                    story.append(Paragraph(f"<b>AI Feedback:</b> {feedbacks[i]}", S["body"]))

        # Footer
        story += [
            Spacer(1, 1*cm),
            HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1")),
            Paragraph(
                f"Generated by AI Interview Coach v2.0 · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                S["footer"]
            ),
        ]

        doc.build(story)
        log.info("Interview report saved: %s", filepath)
        return filepath

    except Exception as e:
        log.error("Interview PDF generation failed: %s", e)
        return ""


def generate_resume_report(analysis_data: dict) -> str:
    """
    Generate a PDF report for a resume ATS analysis.
    Returns the filepath on success, empty string on failure.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import (Paragraph, Spacer, Table, TableStyle,
                                         HRFlowable)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath  = str(REPORTS_DIR / f"resume_report_{timestamp}.pdf")
        doc, S    = _base_doc(filepath, "AI Interview Coach", "Resume ATS Analysis Report")

        ats   = analysis_data.get("ats_score", 0)
        story = [
            Paragraph("AI Interview Coach", S["title"]),
            Paragraph("Resume ATS Analysis Report", S["subtitle"]),
            HRFlowable(width="100%", thickness=1, color=colors.HexColor("#00D4FF")),
            Spacer(1, 0.4*cm),
            Paragraph(f"Overall ATS Score: {ats:.1f} / 100", S["h2"]),
            Spacer(1, 0.3*cm),
        ]

        # Score breakdown table
        breakdown = [
            ["Component",        "Score"],
            ["Keyword Match",    f"{analysis_data.get('keyword_score', 0):.0f}%"],
            ["Format / Structure", f"{analysis_data.get('format_score', 0):.0f}%"],
            ["Length",           f"{analysis_data.get('length_score', 0):.0f}%"],
            ["JD Match",         f"{analysis_data.get('jd_match_score', 0):.0f}%"],
        ]
        from reportlab.lib import colors as c2
        bt = Table(breakdown, colWidths=[9*cm, 8*cm])
        bt.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1E40AF")),
            ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
            ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",   (0,0), (-1,-1), 10),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("GRID",       (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ("TOPPADDING", (0,0), (-1,-1), 6),
            ("BOTTOMPADDING", (0,0), (-1,-1), 6),
        ]))
        story += [bt, Spacer(1, 0.5*cm)]

        # Skills
        skills  = analysis_data.get("skills_found", [])
        missing = analysis_data.get("missing_skills", [])
        if skills:
            story.append(Paragraph("✅  Skills Found", S["h2"]))
            story.append(Paragraph(", ".join(skills), S["body"]))

        if missing:
            story.append(Paragraph("⚠️  Missing Keywords", S["h2"]))
            story.append(Paragraph(", ".join(missing), S["body"]))

        sugg = analysis_data.get("suggestions", "")
        if sugg:
            story.append(Paragraph("💡  AI Recommendations", S["h2"]))
            story.append(Paragraph(sugg, S["body"]))

        story += [
            Spacer(1, 1*cm),
            HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1")),
            Paragraph(
                f"Generated by AI Interview Coach v2.0 · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                S["footer"]
            ),
        ]

        doc.build(story)
        log.info("Resume report saved: %s", filepath)
        return filepath

    except Exception as e:
        log.error("Resume PDF generation failed: %s", e)
        return ""